# -*- coding: utf-8 -*-
"""Die fünf Tätigkeitsberichte. Stil nach dem Muster von Achref Najah:
Präteritum, Ich-Form, Aufbau Ziel -> Randbedingungen -> Vorgehen -> Ergebnis -> Erkenntnis."""

BERICHTE = [
 dict(
  titel="Neuorganisation des Material- und Schraubenlagers nach 5S",
  zeitraum="02.03.2026 – 10.04.2026",
  absaetze=[
   "Zu Beginn meines Praxissemesters bei der Mechanischen Werkstätte Schmidt e.K. beschäftigte ich mich mit der Neuorganisation des Schraubenlagers. Anlass war der Umzug des Lagers vom Erdgeschoss in den Keller, wo sechs neue Regalfächer zur Verfügung standen. Ziel war es, für jede vorhandene Schraubensorte einen festen, beschrifteten und sofort auffindbaren Platz zu schaffen und die Ordnung nach der 5S-Methode aufzubauen.",
   "Zunächst nahm ich den Ausgangszustand auf. Ich besichtigte das bestehende Lager, fotografierte die Situation und vermaß die neuen Regalfächer. Jedes Fach hat eine nutzbare Fläche von 930 × 500 mm. Zusätzlich erfasste ich die im Betrieb bereits verwendeten Sichtlagerkästen, um das vorhandene Behältersystem weiterverwenden zu können.",
   "Im nächsten Schritt führte ich eine vollständige Bestandsaufnahme durch. Ich erfasste alle vorhandenen Schrauben nach Typ, Gewindegröße und Länge und legte dafür in Excel eine Matrix mit den Achsen Gewinde und Länge an. Die Aufnahme erfolgte getrennt nach den vier Schraubentypen: Zylinderkopfschrauben, Sechskantschrauben, Holzschrauben und Schloßschrauben. Insgesamt kam ich auf 135 unterschiedliche Sorten, die ich in 259 Datenpunkten festhielt. Beim anschließenden Prüfen der Daten fand ich drei Rechenfehler in den Ausgangsdateien, die ich korrigierte.",
   "Auf Grundlage der Bestandsdaten wertete ich die Verteilung aus. Ich untersuchte, wie sich die Sorten auf die Schraubentypen und auf die Gewindegrößen verteilen. Dabei zeigte sich ein deutlicher Schwerpunkt bei M8 und M10. Aus dieser Verteilung leitete ich ab, dass drei Behältergrößen sinnvoll sind, und definierte die Größen S, M und L.",
   "Anschließend erstellte ich für jeden der vier Schraubentypen ein eigenes Ordnungskonzept. Für jeden Typ baute ich die vollständige Matrix auf und entwickelte jeweils zwei Schubladenvarianten, die ich hinsichtlich Übersichtlichkeit und Platzausnutzung gegenüberstellte. Danach führte ich alle vier Typen in einer Gesamtmatrix zusammen, legte die Schubladeneinteilung nach Länge fest und ermittelte den Gesamtbedarf an Behältern: 14 kleine, 81 mittlere und 40 große Boxen.",
   "Für die konstruktive Umsetzung legte ich ein Rastermaß von 100 mm fest und definierte die drei Boxgrößen mit 102, 115 und 145 mm. Anschließend konstruierte ich die Behälter im CAD und baute daraus fünf Fach-Varianten mit 12 bis 27 Boxen je Fach auf. Aus diesen Fach-Varianten stellte ich drei komplette Regalvarianten zusammen, die 144, 156 beziehungsweise 162 Boxplätze ergaben.",
   "Zur Auswahl der Vorzugsvariante stellte ich eine Nutzwertanalyse auf. Als Kriterien wählte ich Übersichtlichkeit, Platzausnutzung, Passung zum Bedarf, Erweiterbarkeit und Beschaffungsaufwand und gewichtete sie entsprechend ihrer Bedeutung für den Betrieb. Die Variante mit allen drei Boxgrößen erreichte den höchsten Nutzwert. Sie bietet für jede Schraubenlänge die passende Boxgröße und die beste Übersichtlichkeit. Parallel führte ich einen Kapazitätsnachweis: Die 144 Plätze dieser Variante reichen für die 135 erfassten Sorten aus und lassen zusätzlich Reserve für neue Artikel.",
   "Abschließend erstellte ich einen Belegungsplan, in dem jeder der 135 Sorten ein fester, beschrifteter Platz zugeordnet ist. Der Plan hält für jedes Fach und jede Box fest, welche Sorte dort einzulagern ist, und dient als Arbeitsdokument für den Umzug. Ergänzend recherchierte ich Bezugsquellen und Preise für die Sichtlagerkästen und stellte die Ergebnisse in einer Übersicht zusammen.",
   "Da die Ordnung dauerhaft erhalten bleiben soll, entwarf ich zusätzlich eine Arbeitsanweisung für die Materialentnahme am Schraubenlager. Diese stimmte ich mit meinem Betreuer ab und überarbeitete sie nach seinen Anmerkungen. Parallel begann ich damit, die Lagerbestandsführung digital abzubilden, damit Entnahmen nachvollziehbar erfasst werden können.",
   "Durch diese Tätigkeit lernte ich, wie aus einer unsortierten Ausgangslage über eine systematische Bestandsaufnahme und deren Auswertung ein belastbares Ordnungskonzept entsteht. Besonders wertvoll war die Erfahrung, dass eine Entscheidung wie die Wahl der Boxgrößen nicht nach Gefühl getroffen werden sollte, sondern sich mit einer Nutzwertanalyse und einem Kapazitätsnachweis begründen lässt.",
  ]),
 dict(
  titel="Konzeption und Planung eines Schweißarbeitsplatzes nach 5S",
  zeitraum="13.04.2026 – 08.05.2026",
  absaetze=[
   "Im Anschluss an das Lagerprojekt beschäftigte ich mich mit der Planung eines Schweißarbeitsplatzes. Der Platz sollte von drei Mitarbeitern genutzt werden und auf der vorhandenen Fläche von rund 29 m² untergebracht werden. Ziel war ein vollständig ausgestatteter Arbeitsplatz, der nach der 5S-Methode geordnet ist und die geltenden Sicherheitsanforderungen erfüllt.",
   "Zu Beginn nahm ich den bestehenden Platz auf. Ich besichtigte und fotografierte die Situation, maß die verfügbare Fläche und besprach mit meinem Betreuer, welche Schweißverfahren eingesetzt werden. Im Betrieb wird sowohl mit MAG/MIG als auch mit E-Hand geschweißt. Diese Unterscheidung war für die spätere Ausstattung wichtig, da sich Zubehör, Verbrauchsmaterial und Schutzausrüstung je nach Verfahren unterscheiden.",
   "Der Schwerpunkt der ersten Wochen lag auf der vollständigen Aufnahme des Werkzeugbedarfs. Ich gliederte die Werkzeuge nicht nach Katalog, sondern nach Arbeitsschritt, damit beim Durchgehen sofort auffällt, wenn eine Gruppe Lücken hat. So entstanden neun Kategorien: Schweißen MAG/MIG, Schweißen E-Hand, Spannen und Fixieren, Nachbearbeitung, Anreißen und Messen, persönliche Schutzausrüstung, Sicherheit und Umgebung, Verbrauchsmaterial sowie Ordnung und Lagerung. Bei den Mengen berücksichtigte ich, dass drei Personen den Platz nutzen: persönliche Ausrüstung ist dreifach vorzuhalten, teure Einzelwerkzeuge dagegen nur einmal.",
   "Anschließend führte ich eine Marktrecherche durch. Für jedes Kaufteil stellte ich drei Preisstufen gegenüber, sodass die Beschaffung später ohne weitere Recherche entscheiden kann. Aus den Einzelpreisen leitete ich eine Kostenschätzung für die gesamte Werkzeugausstattung ab.",
   "Für die Gestaltung des Platzes trug ich die ergonomischen Grundmaße zusammen. Ich glich Arbeitshöhe, Greifräume und Beleuchtungsstärke mit den einschlägigen Normvorgaben ab und legte daraus die Maße für Arbeitsfläche und Werkzeugwand fest.",
   "Darauf aufbauend entwickelte ich drei Layout-Konzepte für die Anordnung im Raum und prüfte für jedes die Wege zwischen Schweißtisch, Maschine und Materialablage. Zur Bewertung stellte ich zwei Nutzwertanalysen auf: eine für die Ausführung der Werkbank und eine für das Layout-Konzept. In beiden Fällen legte ich die Kriterien fest, gewichtete sie und bewertete die Varianten mit Punkten. Ergänzend erstellte ich eine Kostenschätzung je Variante, um die technische Bewertung der wirtschaftlichen gegenüberzustellen.",
   "Ein eigener Arbeitsschritt war das 5S-Konzept. Ich legte für jedes Werkzeug einen festen Platz fest und entschied, welche Werkzeuge zur festen Station gehören und welche auf einem mobilen Wagen mitfahren sollen. Für die Werkzeugwand plante ich ein Schattenbrett, bei dem der Umriss jedes Werkzeugs aufgezeichnet ist, sodass ein fehlendes Teil sofort auffällt. Für die Kleinteile plante ich Schubladen mit Schaumeinlagen.",
   "Die Arbeitssicherheit bearbeitete ich als eigenen Schwerpunkt. Ich recherchierte die geltenden Vorschriften und Regelwerke für das Schweißen und ordnete sie den konkreten Maßnahmen am Platz zu, unter anderem Absaugung an der Entstehungsstelle, Schweißschutzvorhang, Feuerlöscher und die vorgeschriebene Schutzausrüstung. Auf dieser Grundlage stellte ich eine Gefährdungsbeurteilung auf, in der ich jede Gefährdung, die mögliche Folge, die Schutzmaßnahme und das verbleibende Restrisiko festhielt.",
   "Zum Abschluss plante ich die Ausstattung der festen Station im Detail: Lochwände, Schubladeneinteilung, Reinigungsplatz, Halterungen für die Schutzausrüstung und die Materialablage. Daraus stellte ich eine Einkaufsliste mit konkreten Produkten zusammen und stimmte sie mit meinem Betreuer ab. Ergänzend erstellte ich eine 5S-Audit-Checkliste, mit der sich der Zustand des Platzes regelmäßig und vergleichbar bewerten lässt, sowie ein Entscheidungsblatt mit den getroffenen Festlegungen. Zusätzlich entwarf ich eine Arbeitsanweisung für das Rüsten und Reinigen des Schweißplatzes.",
   "Durch diese Tätigkeit lernte ich, wie ein Arbeitsplatz als Ganzes geplant wird und wie eng Werkzeugbedarf, Anordnung, Ordnung und Sicherheit zusammenhängen. Mir wurde deutlich, dass Arbeitssicherheit keine nachträgliche Prüfung ist, sondern sich aus Planungsentscheidungen ergibt: Ob ein Feuerlöscher erreichbar ist oder die Wege frei bleiben, entscheidet sich im Layout und nicht in der Gefährdungsbeurteilung.",
  ]),
 dict(
  titel="Konstruktion eines neuen Schweißtisch-Konzepts",
  zeitraum="11.05.2026 – 05.06.2026",
  absaetze=[
   "Aufbauend auf der Planung des Schweißarbeitsplatzes konstruierte ich einen neuen Schweißtisch. Der vorhandene Tisch war für lange Bauteile zu klein und bot keine flexiblen Spannmöglichkeiten. Ziel war ein Tisch, der lange Werkstücke aufnehmen kann, im Normalzustand aber nicht mehr Platz beansprucht als bisher, und der ein Spannsystem für wechselnde Aufspannungen bietet.",
   "Zu Beginn sammelte ich gemeinsam mit meinem Betreuer die Anforderungen und vermaß den vorhandenen Tisch. Zusätzlich nahm ich auf, welche Schwachstellen im Alltag auftreten. Anschließend recherchierte ich bestehende Schweißtisch-Konzepte und Spannsysteme, sammelte Beispiele und bewertete sie hinsichtlich Aufwand und Nutzen für unseren Betrieb.",
   "Auf dieser Grundlage fertigte ich erste Handskizzen an und besprach sie mit meinem Betreuer. Als Grundkonzept legten wir einen beidseitig ausziehbaren Tisch mit Lochplatten-Spannsystem auf einem fahrbaren Untergestell fest. Damit lassen sich lange Teile aufspannen, ohne dass der Tisch dauerhaft die entsprechende Fläche belegt.",
   "Für das Spannsystem führte ich eine Marktrecherche zu Lochplatten durch. Ich verglich mehrere Angebote hinsichtlich Lochraster, Plattenstärke, Werkstoff und Preis und wählte ein Raster mit 16 mm Bohrungsdurchmesser aus. Dieses Raster ist im Markt verbreitet, sodass Spannmittel und Vorrichtungen als Zukaufteile verfügbar sind.",
   "Anschließend begann ich mit der CAD-Konstruktion. Zuerst baute ich die Tischplatte mit dem Lochraster auf. Danach konstruierte ich das Oberteil mit Trägern und Profilen sowie das Unterteil mit Beinen, Streben und Fußplatten. Für jedes Bauteil vergab ich eine Teilenummer, um die spätere Zuordnung in den Stücklisten sicherzustellen.",
   "Ein eigener Konstruktionsschwerpunkt war das Erweiterungssystem. Ich führte es als Teleskop-Rahmen aus, der sich beidseitig ausziehen lässt. Nach dem Zusammenführen aller Baugruppen zum Gesamtzusammenbau prüfte ich im Modell die Verfahrwege und mögliche Kollisionen und passte die Führungen entsprechend an.",
   "Aus dem Modell leitete ich anschließend die Zeichnungen ab. Ich erstellte Einzelteil- und Baugruppenzeichnungen, bemaßte sie und füllte die Schriftfelder aus. Parallel entstanden die Stücklisten, in denen ich die Zukaufteile kennzeichnete. Aus den Stücklisten leitete ich den Materialbedarf ab und stellte die benötigten Rohrlängen zusammen. Zusätzlich legte ich die Lenkrollen aus und prüfte ihre Tragfähigkeit gegen das errechnete Gesamtgewicht.",
   "Bevor ich den Zeichnungssatz weitergab, prüfte ich ihn systematisch selbst. Dabei fielen mir Abweichungen bei den Gewichtsangaben auf. Ich rechnete die Gewichte einzelner Teile aus Querschnitt, Länge und Dichte nach und stellte fest, dass dasselbe Bauteil an zwei Stellen mit unterschiedlichen Gewichten geführt war. Bei der weiteren Durchsicht fand ich zusätzlich einen Längenwiderspruch sowie Baugruppen, die ohne Gewichtsangabe ausgewiesen waren. Insgesamt dokumentierte ich fünf belegte Fehler.",
   "Alle gefundenen Fehler arbeitete ich anschließend im CAD-Modell und in den Stücklisten ein. Aus dem korrigierten Stand erstellte ich die Hauptstückliste neu und ergänzte für jede Position, ob sie selbst gefertigt oder zugekauft wird. Den korrigierten Zeichnungssatz besprach ich mit meinem Betreuer und übergab ihn zur Prüfung.",
   "Durch diese Tätigkeit erhielt ich einen umfassenden Einblick in den Ablauf einer Konstruktion von der Anforderungsaufnahme über das CAD-Modell bis zum fertigungsreifen Zeichnungssatz. Die wichtigste Erfahrung war die eigene Prüfung: Das Modell sah lange fertig aus, und erst das Nachrechnen der Gewichte machte sichtbar, dass es das noch nicht war.",
  ]),
 dict(
  titel="Optimierung des Schweißmaschinen-Wagens und der Werkzeugplätze nach 5S",
  zeitraum="08.06.2026 – 26.06.2026",
  absaetze=[
   "Als mobile Ergänzung zur festen Schweißstation befasste ich mich mit der Optimierung des Schweißmaschinen-Wagens. Der Wagen soll Schweißgerät, Gasflasche und die wichtigsten Werkzeuge zum Werkstück bringen, damit nicht das Werkstück zur Maschine transportiert werden muss. Ziel war ein Wagen, auf dem jedes Werkzeug einen festen Platz hat und der die Anforderungen an Standsicherheit und Gasflaschensicherung erfüllt.",
   "Zunächst nahm ich den vorhandenen Wagen auf. Ich fotografierte ihn im Betrieb und dokumentierte seinen Zustand. Anschließend vermaß ich das Schweißgerät und die Gasflasche vor Ort und hielt die Maße in einer Handskizze fest. Aus diesen Maßen erstellte ich vereinfachte CAD-Platzhalter für Gerät und Flasche, um den benötigten Bauraum in den späteren Entwürfen realistisch abzubilden.",
   "Auf Basis der Aufnahme stellte ich eine Anforderungsliste auf. Ich unterschied dabei zwischen dem, was der Wagen tragen muss, und dem, was er können muss. Die Liste brachte ich auf 14 nummerierte und einzeln prüfbare Anforderungen und stimmte sie mit meinem Betreuer ab. Dadurch konnte ich jeden späteren Entwurf gegen dieselben Kriterien bewerten.",
   "Danach recherchierte ich vergleichbare Projekte und sammelte fünf mögliche Designrichtungen. Aus dieser Recherche entwickelte ich zwei erste Entwürfe im CAD und stellte sie einander gegenüber: einen schlanken Kompaktrahmen und einen breiteren Werkstattwagen mit Lochblechwänden. Der Kompaktrahmen erwies sich als kippgefährdet und bot zu wenig Ablagefläche, der Werkstattwagen war in der Grundrichtung passend, aber zu lang.",
   "Anschließend legte ich Maße und Ergonomie fest und schätzte das Gewicht des beladenen Wagens ab, um daraus die erforderliche Tragfähigkeit der Rollen abzuleiten. Auf dieser Grundlage konstruierte ich als erste Variante einen kompletten Neubau mit eigenem Gerätefach und erstellte einen Belegungsplan, der jedem der 16 vorgesehenen Werkzeuge eine feste Position zuweist.",
   "Beim Abgleich der Maße stellte ich fest, dass das geplante Gerätefach niedriger war als die vorhandene Schweißmaschine. Die Maschine hätte also nicht hineingepasst. Dieser Befund führte zu einem Konzeptwechsel: Statt eines kompletten Neubaus entwarf ich ein Aufsatzgestell, das über den vorhandenen Wagen fährt und ihn überspannt. Damit bleibt die Maschine auf ihrem angestammten Fahrgestell und der Maßkonflikt entfällt.",
   "Diese Variante überarbeitete ich in einer zweiten Version so, dass die Gasflasche innerhalb der Radaufstandsfläche steht. In der ersten Version stand sie seitlich außerhalb, was zu einer ungünstigen Lastverteilung und zu einer großen Baubreite geführt hätte.",
   "Als Vorzugsvariante legte ich schließlich einen modularen Aufbau in vier Etagen fest: unten die Aufnahme für Maschine und Bestandswagen, darüber zwei Schubladenetagen und oben ein Deckel mit anhängbarer Lochwand. Der Vorteil dieses Aufbaus liegt in der Modularität: Jede Etage ist eine eigene Baugruppe, und die beiden Schubladenetagen sind identisch, sodass nur eine Konstruktion in doppelter Stückzahl gefertigt werden muss.",
   "Aus dem Modell leitete ich die Zeichnungen für die Einzelteile ab, bemaßte sie und erstellte die Baugruppenzeichnungen sowie die Gesamtstückliste. Anschließend prüfte ich den Zeichnungssatz selbst. Beim Nachrechnen der Gewichte fand ich auf zwei Blättern Abweichungen zwischen der Zeichnungsangabe und dem rechnerischen Wert. Diese und weitere Befunde dokumentierte ich und ordnete sie nach Priorität, damit sie vor der Fertigung abgearbeitet werden können. Abschließend legte ich die 5S-Zuordnung der Werkzeuge auf dem Wagen fest und entwarf eine Arbeitsanweisung für das Rüsten.",
   "Durch diese Tätigkeit lernte ich, wie wichtig eine saubere Aufnahme des Ist-Zustands ist. Der entscheidende Maßkonflikt wurde nur deshalb rechtzeitig sichtbar, weil ich Gerät und Flasche vorher real vermessen hatte. Außerdem erfuhr ich, dass ein Konzeptwechsel kein Rückschritt ist, sondern die richtige Konsequenz aus einem gemessenen Widerspruch.",
  ]),
 dict(
  titel="Konzeption und Planung eines Zerspanarbeitsplatzes",
  zeitraum="29.06.2026 – 17.07.2026",
  absaetze=[
   "Den letzten Projektabschnitt meines Praktikums bildete die Planung eines Arbeitsplatzes zum konventionellen Drehen und Fräsen. Der Platz wird von drei Personen in einer Schicht genutzt. Ziel war ein vollständig ausgestatteter Zerspanarbeitsplatz, der nach der 5S-Methode geordnet ist und für den mehrere Ausführungsvarianten technisch und wirtschaftlich verglichen werden.",
   "Zu Beginn nahm ich die Rahmenbedingungen auf. Ich besichtigte den bestehenden Bereich, fotografierte die Maschinen und die vorhandene Ausstattung und hielt fest, welche Arbeiten dort tatsächlich anfallen. Aus den Rahmenbedingungen ergaben sich bereits die ersten Festlegungen: Da drei Personen gleichzeitig arbeiten, muss personengebundenes Handwerkzeug mehrfach vorhanden sein, während die Werkbank zentral für alle drei ausgelegt wird.",
   "Anschließend stellte ich den vollständigen Werkzeugbedarf zusammen. Ich gliederte ihn nach Arbeitsschritt in sechs Gruppen: Werkzeuge zum Drehen, Werkzeuge zum Fräsen, Spann- und Aufspannmittel, Mess- und Prüfmittel, Nacharbeit sowie Hilfsmittel. Für jede Position legte ich die benötigte Menge fest und begründete sie. Messschieber, Entgratwerkzeug und Handwerkzeug führte ich dreifach, teure Einzelstücke wie Schraubstock oder Teilapparat dagegen nur einmal.",
   "Danach recherchierte ich die Preise und bepreiste die Werkzeugliste vollständig. Sie umfasst 35 Positionen. Die Kosten wertete ich nach Kategorien aus und stellte fest, dass Fräsen und Spannen zusammen knapp die Hälfte der Werkzeugkosten ausmachen, während die im Alltag ständig gebrauchte Nacharbeit die günstigste Gruppe ist.",
   "Für die Ordnung am Platz arbeitete ich ein Zonenkonzept aus. Ich ordnete jedes Werkzeug nach seiner Nutzungshäufigkeit einer von drei Zonen zu: täglich gebrauchte Werkzeuge an die Lochwand in Griffhöhe, wöchentlich gebrauchte in die Schubladen und selten gebrauchte in den Schrank. Für jede Zuordnung hielt ich die Begründung fest, damit die Ordnung später nachvollziehbar bleibt.",
   "Anschließend legte ich die Grundmaße der Werkbank fest und glich sie mit den Ergonomienormen ab. Die Arbeitshöhe leitete ich aus der Ellenbogenhöhe ab, die Tiefe begrenzte ich auf 600 mm, damit die Greifwege kurz bleiben. Zusätzlich ermittelte ich den erforderlichen Beleuchtungswert für die anfallenden Arbeiten.",
   "Für den Vergleich entwickelte ich vier Bauvarianten – Aluminium-Nutprofil, Stahl-Standardwerkbank, Systemmodule und Eigenbau als Schweißkonstruktion – und stellte sie mit ihren Vor- und Nachteilen gegenüber. Unabhängig davon entwarf ich vier Layout-Konzepte für die Anordnung im Raum. Zusätzlich zeichnete ich einen maßstäblichen Werkstatt-Grundriss und prüfte darin die Freiräume an den Maschinen für Bedienung, Sicherheit und Späneabfuhr.",
   "Zur Bewertung stellte ich eine Nutzwertanalyse auf. Ich legte sieben Kriterien fest, gewichtete sie und bewertete jede Variante mit Punkten. Bei der Auswertung zeigte sich, dass die beiden bestplatzierten Varianten nur um wenige Hundertstel auseinanderliegen. Diesen geringen Abstand hielt ich ausdrücklich fest, da er bei geschätzten Einzelnoten keine belastbare Entscheidung trägt. Die Analyse schließt damit zwei Varianten sicher aus, die endgültige Wahl zwischen den beiden verbleibenden muss über reale Angebote erfolgen.",
   "Ergänzend rechnete ich die Wirtschaftlichkeit. Als messbaren Nutzen setzte ich die durch die feste Ordnung eingesparte Suchzeit an, bewertete sie mit dem Stundensatz und stellte sie der Investition gegenüber. Zusätzlich rechnete ich die Amortisation für mehrere Annahmen durch, um zu prüfen, wie stark das Ergebnis von der geschätzten Zeitersparnis abhängt. Auch im vorsichtigsten Fall bleibt die Investition wirtschaftlich. Abschließend stellte ich eine Gefährdungsbeurteilung für den Zerspanplatz auf, ordnete die Maßnahmen nach dem STOP-Prinzip und erstellte einen Zeitplan, eine 5S-Audit-Checkliste sowie das Entscheidungsblatt.",
   "Durch diese Tätigkeit lernte ich, wie eine Investitionsentscheidung technisch und wirtschaftlich vorbereitet wird. Am meisten mitgenommen habe ich die Einsicht, dass auch ein knappes Ergebnis ein Ergebnis ist: Eine Nutzwertanalyse ehrlich zu lesen und ihre Grenzen zu benennen, ist wertvoller, als einen Sieger auszurufen, den die Zahlen nicht hergeben.",
  ]),
]
