# -*- coding: utf-8 -*-
"""Tagestexte für den Tätigkeitsnachweis, nach Phasen geordnet.
Reihenfolge = Reihenfolge der Arbeitstage innerhalb der Phase."""

EINARBEITUNG = [
 "Begrüßung und Einführung im Betrieb, Rundgang durch Werkstatt, Lager und Büro. Teilnahme an der Sicherheitsunterweisung und Einweisung in die Hausordnung.",
 "Unterweisung an den Maschinen und Arbeitsplätzen durch den Betreuer (Dreh- und Fräsmaschine, Schweißplätze, Trennschleifer). Persönliche Schutzausrüstung erhalten und angepasst.",
 "Arbeitsplatz und Rechner eingerichtet, Zugänge zur CAD-Software und zu den Netzlaufwerken eingerichtet. Ablagestruktur für die Praktikumsdokumentation angelegt.",
 "Aufgaben des Praxissemesters mit dem Betreuer besprochen und die fünf Themen zeitlich grob eingeordnet. Abläufe von der Auftragsannahme bis zur Auslieferung erklärt bekommen.",
 "Bei laufenden Arbeiten in der Werkstatt zugesehen und mitgeholfen, um Material, Werkzeuge und die üblichen Arbeitsschritte kennenzulernen. Erste Fotos für die Dokumentation gemacht.",
]

SCHRAUBENLAGER = [
 "Aufgabenstellung zum Schraubenlager erhalten und mit dem Betreuer besprochen. Das neue Regal im Keller angeschaut und vermessen (6 Fächer, je 930 × 500 mm).",
 "Ausgangszustand des bestehenden Lagers fotografiert und dokumentiert. Vorhandene Behälter und das Bito-Box-Prinzip erfasst.",
 "Bestandsaufnahme begonnen: Zylinderkopfschrauben nach Gewinde (M5–M20) und Länge erfasst. Matrix-Struktur Gewinde × Länge in Excel angelegt.",
 "Bestandsaufnahme der Zylinderkopfschrauben abgeschlossen und die Werte stichprobenartig gegengeprüft.",
 "Sechskantschrauben nach Gewinde und Länge aufgenommen und in die Matrix eingetragen.",
 "Holzschrauben aufgenommen und eingetragen. Sortiment auf Doppelungen und nicht mehr verwendete Größen geprüft.",
 "Schloßschrauben aufgenommen. Damit sind alle vier Schraubentypen erfasst — insgesamt 135 Sorten.",
 "Beim Prüfen der Aufnahmedaten drei Rechenfehler in den Ausgangsdateien gefunden und korrigiert.",
 "Bestand ausgewertet: Verteilung nach Schraubentyp, Gewindegröße und Länge zusammengestellt.",
 "ABC-Analyse durchgeführt (Schwerpunkt M8 und M10) und daraus die drei Boxgrößen S, M und L abgeleitet.",
 "Ordnungskonzept für die Zylinderkopfschrauben erstellt: vollständige Matrix aufgebaut sowie zwei Schubladenvarianten entwickelt und verglichen.",
 "Ordnungskonzept für die Sechskantschrauben erstellt und die Varianten gegenübergestellt.",
 "Ordnungskonzept für die Holzschrauben erstellt.",
 "Ordnungskonzept für die Schloßschrauben erstellt. Damit sind alle vier Typen einzeln durchgeplant.",
 "Alle vier Typen in einer Gesamtmatrix zusammengeführt und die Schubladeneinteilung nach Länge festgelegt.",
 "Gesamtbedarf an Boxen ermittelt: 14 kleine, 81 mittlere und 40 große Behälter.",
 "Boxen- und Regallayout geplant: Rastermaß 100 mm festgelegt, Boxgrößen S/M/L mit 102, 115 und 145 mm definiert.",
 "Anzahl der Boxen je Fach skizziert und mit den gemessenen Regalmaßen abgeglichen.",
 "Mit der CAD-Konstruktion begonnen und die drei Boxgrößen als Modelle aufgebaut.",
 "Fach-Varianten im CAD konstruiert, von 12 bis 27 Boxen je Fach.",
 "Drei komplette Regalvarianten modelliert und die Boxplätze gezählt (144, 156 und 162 Plätze).",
 "Kapazitätsnachweis gerechnet: 144 Plätze reichen für die 135 erfassten Sorten.",
 "Nutzwertanalyse der drei Regalvarianten aufgestellt, Kriterien gewichtet und die Variante S · M · L als Empfehlung begründet.",
 "Belegungsplan erstellt: jeder der 135 Sorten einen festen, beschrifteten Platz zugeordnet.",
 "Belegungsplan mit dem Betreuer durchgesprochen und die offenen Punkte zur S/M/L-Verteilung festgehalten.",
 "Bezugsquellen und Preise für die Sichtlagerkästen recherchiert und in einer Übersicht zusammengestellt.",
 "Arbeitsanweisung für die Materialentnahme am Schraubenlager entworfen.",
 "Arbeitsanweisung zur Materialentnahme mit dem Betreuer abgestimmt und nach seinen Anmerkungen überarbeitet.",
 "Excel-Datei zur Lagerbestandsführung begonnen: Artikelliste mit Barcode, Bezeichnung, Maß und Bestand angelegt.",
 "Dokumentation des Lagerkonzepts zusammengeschrieben, Abbildungen und Tabellen eingefügt.",
 "Ergebnisse des Lagerprojekts dem Betreuer vorgestellt und das weitere Vorgehen für die Beschaffung besprochen.",
 "Restarbeiten am Lagerkonzept erledigt und die Unterlagen für die Übergabe sortiert.",
]

SCHWEISSARBEITSPLATZ = [
 "Aufgabenstellung zum Schweißarbeitsplatz erhalten. Bestehenden Platz besichtigt, fotografiert und die verfügbare Fläche aufgemessen (rund 29 m²).",
 "Verwendete Schweißverfahren mit dem Betreuer besprochen (MAG/MIG und E-Hand) und die Unterschiede für die spätere Ausstattung festgehalten.",
 "Aufnahme der vorhandenen Werkzeuge am Schweißplatz begonnen und nach Verwendungszweck gruppiert.",
 "Werkzeugaufnahme fortgesetzt: Kategorien Schweißen MAG/MIG und Schweißen E-Hand vollständig erfasst.",
 "Kategorien Spannen und Fixieren sowie Nachbearbeitung erfasst und mit den Mitarbeitern auf Vollständigkeit geprüft.",
 "Kategorien Anreißen und Messen sowie persönliche Schutzausrüstung für drei Personen zusammengestellt.",
 "Kategorien Sicherheit und Umgebung, Verbrauchsmaterial sowie 5S-Möbel ergänzt. Damit sind alle neun Werkzeugkategorien A bis I erfasst.",
 "Marktrecherche zu den Werkzeugen begonnen und Richtpreise je Position gesammelt.",
 "Marktrecherche abgeschlossen und je Kaufteil drei Preisstufen gegenübergestellt.",
 "Ergonomische Grundmaße für den Arbeitsplatz zusammengetragen (Arbeitshöhe, Greifräume, Beleuchtung) und mit den Normvorgaben abgeglichen.",
 "Erstes Layout-Konzept für den Platz gezeichnet und die Wege zwischen Tisch, Maschine und Materialablage geprüft.",
 "Zwei weitere Layout-Varianten entwickelt und die drei Konzepte nebeneinandergestellt.",
 "Nutzwertanalyse für die Werkbank-Ausführung aufgestellt: Kriterien festgelegt und gewichtet.",
 "Nutzwertanalyse für das Layout-Konzept gerechnet und die Ergebnisse ausgewertet.",
 "Kostenschätzung je Variante erstellt und der Nutzwertanalyse gegenübergestellt.",
 "5S-Konzept für den Schweißplatz ausgearbeitet: feste Plätze, Schattenbrett und Beschriftung festgelegt.",
 "Aufteilung zwischen fester Station und mobilem Wagen festgelegt und je Werkzeug zugeordnet.",
 "Sicherheitsanforderungen recherchiert und den Maßnahmen zugeordnet (Absaugung, Schweißvorhang, PSA, Feuerlöscher).",
 "Gefährdungsbeurteilung für den Schweißplatz aufgestellt und die Restrisiken bewertet.",
 "Arbeitsanweisung für das Rüsten und Reinigen des Schweißplatzes entworfen.",
 "Lochwände und Schubladeneinteilung der festen Station geplant und die Kaufteile ausgewählt.",
 "Einkaufsliste für die Station zusammengestellt und mit dem Betreuer abgestimmt.",
 "5S-Audit-Checkliste für den Schweißplatz erstellt und das Entscheidungsblatt ausgefüllt.",
 "Dokumentation des Schweißarbeitsplatz-Konzepts geschrieben und dem Betreuer vorgestellt.",
]

SCHWEISSTISCH = [
 "Aufgabenstellung zum neuen Schweißtisch erhalten. Anforderungen mit dem Betreuer gesammelt: Größe, Spannmöglichkeiten, Fahrbarkeit.",
 "Vorhandenen Tisch vermessen und die Schwachstellen im Betrieb aufgenommen.",
 "Recherche zu Schweißtisch-Konzepten und Spannsystemen durchgeführt, Beispiele gesammelt und bewertet.",
 "Erste Handskizzen für den neuen Tisch angefertigt und mit dem Betreuer besprochen.",
 "Grundkonzept festgelegt: ausziehbarer Tisch mit Lochplatten-Spannsystem auf fahrbarem Untergestell.",
 "Marktrecherche zu Lochplatten durchgeführt, Angebote verglichen und das D16-Raster ausgewählt.",
 "Mit der CAD-Konstruktion begonnen: Tischplatte mit Lochraster aufgebaut.",
 "Oberteil konstruiert: Träger und Profile modelliert und die Teilenummern vergeben.",
 "Unterteil konstruiert: Beine, Streben und Fußplatten aufgebaut.",
 "Erweiterungssystem als Teleskop-Rahmen konstruiert, beidseitig ausziehbar.",
 "Baugruppen zum Gesamtzusammenbau zusammengeführt und die Struktur geordnet.",
 "Kollisionen und Verfahrwege im Modell geprüft und die Führungen angepasst.",
 "Erste Zeichnungsblätter abgeleitet und bemaßt.",
 "Weitere Einzelteilzeichnungen erstellt und die Schriftfelder ausgefüllt.",
 "Stücklisten der Baugruppen erstellt und die Zukaufteile gekennzeichnet.",
 "Materialbedarf aus den Stücklisten abgeleitet und die Rohrlängen zusammengestellt.",
 "Lenkrollen ausgelegt und gegen das errechnete Gesamtgewicht geprüft.",
 "Zeichnungssatz vollständig durchgesehen und dabei Abweichungen bei den Gewichtsangaben gefunden.",
 "Gewichte einzelner Teile nachgerechnet und die gefundenen Fehler dokumentiert.",
 "Weitere Prüfung des Zeichnungssatzes: Längenwiderspruch und Baugruppen ohne Gewichtsangabe festgestellt.",
 "Korrekturen im CAD-Modell und in den Stücklisten eingearbeitet.",
 "Korrigierte Hauptstückliste erstellt und die Make-or-Buy-Zuordnung ergänzt.",
 "Zeichnungssatz mit dem Betreuer durchgesprochen und zur Prüfung übergeben.",
 "Dokumentation des Schweißtisch-Projekts zusammengeschrieben und die Abbildungen eingefügt.",
]

SCHWEISSWAGEN = [
 "Aufgabenstellung zum Schweißmaschinenwagen erhalten. Vorhandenen Wagen im Betrieb fotografiert und den Zustand aufgenommen.",
 "Schweißgerät und Gasflasche vor Ort aufgemessen und die Maße in einer Handskizze festgehalten.",
 "Vereinfachte CAD-Platzhalter für Gerät und Flasche erstellt, um den Bauraum abzubilden.",
 "Anforderungsliste aufgestellt: was der Wagen tragen und was er können muss.",
 "Anforderungsliste auf 14 nummerierte Punkte gebracht und mit dem Betreuer abgestimmt.",
 "Referenzprojekte recherchiert und fünf Designrichtungen für den Wagen gesammelt.",
 "Zwei erste Entwürfe im CAD aufgebaut und gegenübergestellt.",
 "Maße und Ergonomie festgelegt, Gewicht des beladenen Wagens grob abgeschätzt.",
 "Kompletten Neubau als Variante A konstruiert und einen Belegungsplan mit 16 Werkzeugpositionen erstellt.",
 "Beim Maßabgleich festgestellt, dass das geplante Gerätefach zu niedrig für die vorhandene Maschine ist.",
 "Als Variante B ein Aufsatzgestell entworfen, das über den vorhandenen Wagen fährt.",
 "Variante B überarbeitet, sodass die Gasflasche innerhalb der Aufstandsfläche steht.",
 "Vorzugsvariante festgelegt: modularer Aufbau in vier Etagen.",
 "Etagen im CAD konstruiert: Aufnahme unten, zwei Schubladenetagen, Deckel mit Lochwand.",
 "Zeichnungsblätter für die Einzelteile abgeleitet und bemaßt.",
 "Baugruppenzeichnungen und Gesamtstückliste erstellt.",
 "Zeichnungssatz geprüft: Gewichtsangaben nachgerechnet und Abweichungen auf zwei Blättern gefunden.",
 "Weitere Befunde dokumentiert und die offenen Punkte nach Priorität geordnet.",
 "5S-Zuordnung der Werkzeuge auf dem Wagen festgelegt und beschriftet.",
 "Arbeitsanweisung für das Rüsten des Schweißwagens entworfen.",
 "Ergebnisse zusammengefasst und dem Betreuer vorgestellt.",
]

ZERSPANARBEITSPLATZ = [
 "Aufgabenstellung zum Zerspanarbeitsplatz erhalten und die Rahmenbedingungen aufgenommen (Drehen und Fräsen, drei Personen, eine Schicht).",
 "Bestehenden Platz besichtigt, Maschinen und vorhandene Ausstattung fotografiert.",
 "Werkzeugbedarf für das Drehen zusammengestellt.",
 "Werkzeugbedarf für das Fräsen sowie die Spann- und Aufspannmittel erfasst.",
 "Mess- und Prüfmittel sowie Nacharbeit und Hilfsmittel ergänzt. Damit sind alle sechs Gruppen erfasst.",
 "Mengen je Position festgelegt und begründet, welche Werkzeuge dreifach beschafft werden müssen.",
 "Preise recherchiert und die Werkzeugliste mit 35 Positionen bepreist.",
 "Kosten nach Kategorien ausgewertet und die teuersten Positionen herausgearbeitet.",
 "5S-Ordnung ausgearbeitet und die Werkzeuge den Zonen A, B und C zugeordnet.",
 "Grundmaße der Werkbank festgelegt und mit den Ergonomienormen abgeglichen.",
 "Vier Bauvarianten skizziert und in 3D dargestellt: Aluprofil, Stahl-Standard, Systemmodule und Eigenbau.",
 "Vier Layout-Konzepte entwickelt und die Vor- und Nachteile gegenübergestellt.",
 "Werkstatt-Grundriss maßstäblich gezeichnet und die Freiräume an den Maschinen geprüft.",
 "Nutzwertanalyse aufgestellt: sieben Kriterien festgelegt und gewichtet.",
 "Bewertungsmatrix gerechnet und die Rangfolge der vier Varianten ausgewertet.",
 "Wirtschaftlichkeit gerechnet: eingesparte Suchzeit gegen die Investition gestellt und die Amortisation ermittelt.",
 "Gefährdungsbeurteilung für den Zerspanplatz aufgestellt und die Maßnahmen nach dem STOP-Prinzip geordnet.",
 "Zeitplan für die Umsetzung erstellt und die 5S-Audit-Checkliste ausgearbeitet.",
 "Entscheidungsblatt ausgefüllt und die offenen Punkte für die Beschaffung zusammengestellt.",
 "Dokumentation des Zerspanarbeitsplatzes geschrieben und dem Betreuer vorgestellt.",
]

ROSTSCHUTZ = [
 "Aufgabenstellung zum Rostschutz für die Schienenprofile erhalten. Lagerbedingungen der Profile im Betrieb aufgenommen und fotografiert.",
 "Bestehende Rostschäden begutachtet und die Ursachen mit den Mitarbeitern besprochen (Feuchtigkeit, Kondenswasser, Lagerdauer).",
 "Recherche zu Korrosionsschutzverfahren durchgeführt: Ölen, Wachsen, VCI-Folie und trockene Lagerung verglichen.",
 "Verfahren gegenübergestellt und nach Wirksamkeit, Aufwand und Kosten bewertet.",
 "Konzept für eine geschlossene Lagerbox mit VCI-Schutz entworfen und die benötigten Maße aufgenommen.",
 "Lagerbox im CAD konstruiert und die Aufteilung für die verschiedenen Profillängen festgelegt.",
 "Material- und Kostenaufstellung für die Schutzbox erstellt.",
 "Zeitersparnis durch den Wegfall des Nacharbeitens abgeschätzt und der Investition gegenübergestellt.",
 "Arbeitsanweisung für die Einlagerung und Entnahme der Schienenprofile entworfen.",
 "Rostschutz-Konzept zusammengeschrieben, dem Betreuer vorgestellt und die Praktikumsunterlagen abschließend sortiert.",
]

PHASENTEXTE = {
 "Einarbeitung": EINARBEITUNG,
 "Schraubenlager": SCHRAUBENLAGER,
 "Schweissarbeitsplatz": SCHWEISSARBEITSPLATZ,
 "Schweisstisch": SCHWEISSTISCH,
 "Schweisswagen": SCHWEISSWAGEN,
 "Zerspanarbeitsplatz": ZERSPANARBEITSPLATZ,
 "Rostschutz": ROSTSCHUTZ,
}
